/*
 * Copyright (C) 2018 Miquel Sas
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */
package com.mlt.desktop.control.table;

/**
 * Listener of events generated by the table component.
 * 
 * @author Miquel Sas
 */
public interface TableCmpListener {
	/**
	 * Fired when the cell focus changes.
	 * 
	 * @param tableCmp The table.
	 */
	void focusCellChanged(TableCmp tableCmp);

	/**
	 * Fired when the rows or columns selected change.
	 * 
	 * @param tableCmp The table.
	 */
	void selectionChanged(TableCmp tableCmp);
}
